version: '3.4'

services:
  database_sql:
    image: ${DOCKER_REGISTRY-}databasesql
    build:
      context: .\Database_sql
      dockerfile: Dockerfile
    ports:
        - "8000:80"
  backend:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "Docker123!"
        ACCEPT_EULA: "Y"
    ports:
        - "1440:1433"